### ISSUE TITLE
Improve test coverage for fill

### ISSUE THREAD

**Issue by VantorreWannes** [JokNavi/deltas#1]
## Todo

- [x] Improve test coverage for Instruction.non_default_item_count()
- [x] Bugfix and improve test coverage for Instruction.threshold()
- [x] Bugfix and improve test coverage for Instruction.fill()
