### ISSUE TITLE
Finish new method

### ISSUE THREAD

**Issue by VantorreWannes** [JokNavi/deltas#2]
## Todo

- [x] Finish the Patch::construct_instructions() method
- [x] Test the Patch::construct_instructions() method
- [x] Impl Patch::new() calling Patch::construct_instructions()
